"""Headless Codex provider (``codex exec --json``).

Codex assigns its own thread id and reports it in ``thread.started``.  The
``on_session_started`` callback lets the orchestrator checkpoint that id as
soon as it is known, preserving GoaLoop's crash/resume behavior.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from typing import Callable, TextIO

from .agent import (
    AgentResult,
    QUOTA_RE,
    QuotaExhausted,
    SessionStarted,
    TRANSIENT_RE,
    TransientError,
)


def _clip(text: str, n: int) -> str:
    return text if len(text) <= n else text[:n] + f"… (+{len(text) - n} chars)"


class CodexAdapter:
    """Runs one non-interactive Codex turn and normalizes its JSONL events."""

    provider = "codex"
    reports_cost = False

    def __init__(
        self,
        cwd: str,
        system_prompt: str | None = None,
        model: str | None = None,
        log: Callable[[str], None] = print,
    ):
        self.cwd = cwd
        self.system_prompt = system_prompt
        self.model = model
        self.log = log

    def allocate_session_id(self) -> None:
        """Codex thread ids are generated by the CLI after it starts."""

        return None

    def _build_args(
        self, prompt: str, session_id: str | None, resume: bool
    ) -> list[str]:
        if resume and not session_id:
            raise ValueError("resuming Codex requires a session id")
        if not resume and session_id:
            raise ValueError("a new Codex session id is assigned by codex exec")

        args = ["codex", "exec"]
        if resume:
            args.append("resume")

        # GoaLoop workers are unattended and historically run with Claude's
        # permission checks disabled.  Use Codex's equivalent on both initial
        # and resumed turns; unlike --sandbox, this flag is accepted by
        # ``codex exec resume`` too.
        args += [
            "--json",
            "--dangerously-bypass-approvals-and-sandbox",
            "--skip-git-repo-check",
        ]
        if self.model:
            args += ["--model", self.model]

        if resume:
            assert session_id is not None
            args += [session_id, prompt]
        else:
            # codex exec has no append-system-prompt flag.  Put the stable
            # Runner protocol before the per-attempt brief on the first turn;
            # resumed turns already retain it in the thread.
            initial_prompt = (
                f"{self.system_prompt}\n\n---\n\n{prompt}"
                if self.system_prompt
                else prompt
            )
            args.append(initial_prompt)
        return args

    def run(
        self,
        prompt: str,
        session_id: str | None = None,
        resume: bool = False,
        stderr: TextIO | int | None = None,
        on_session_started: SessionStarted | None = None,
    ) -> AgentResult:
        args = self._build_args(prompt, session_id, resume)
        resolved = shutil.which(args[0])
        if resolved:
            args[0] = resolved

        env = dict(os.environ)
        # This variable describes a parent Codex turn and should not be
        # inherited as the identity of the independent worker process.
        env.pop("CODEX_THREAD_ID", None)

        label = session_id[:8] if session_id else "new"
        self.log(f"[runner] codex exec (session={label}, resume={resume})")

        capture = tempfile.TemporaryFile(mode="w+") if stderr is None else None
        child_stderr = capture if capture is not None else stderr

        try:
            proc = subprocess.Popen(
                args,
                cwd=self.cwd,
                env=env,
                stdout=subprocess.PIPE,
                stderr=child_stderr,
                stdin=subprocess.DEVNULL,
                text=True,
                bufsize=1,
            )
        except FileNotFoundError as e:
            raise TransientError(
                f"codex executable not found ({args[0]!r}); will back off "
                f"and retry: {e}",
                session_id,
            ) from e

        (
            result_text,
            active_session_id,
            error_text,
        ) = self._parse_stream(
            proc, session_id if resume else None, on_session_started
        )
        self._wait_for_exit(proc)

        stderr_text = ""
        if capture is not None:
            try:
                capture.seek(0)
                stderr_text = capture.read()
            finally:
                capture.close()

        primary = "\n".join(s for s in (error_text, stderr_text) if s)
        if primary and QUOTA_RE.search(primary):
            raise QuotaExhausted(primary.strip()[:300])
        if primary and TRANSIENT_RE.search(primary):
            raise TransientError(primary.strip()[:300], active_session_id)

        if not active_session_id:
            raise RuntimeError("codex exec produced no thread.started event")
        if proc.returncode and not result_text:
            detail = primary.strip()[:200]
            raise RuntimeError(
                f"codex exec exited {proc.returncode} with no result"
                + (f": {detail}" if detail else "")
            )
        if not result_text:
            detail = error_text.strip()[:200]
            raise RuntimeError(
                "codex exec completed with no agent message"
                + (f": {detail}" if detail else "")
            )

        return AgentResult(text=result_text, session_id=active_session_id)

    def _parse_stream(
        self,
        proc: subprocess.Popen,
        session_id: str | None,
        on_session_started: SessionStarted | None,
    ) -> tuple[str, str | None, str]:
        """Return ``(final_message, thread_id, provider_errors)``."""

        result_text = ""
        active_session_id = session_id
        errors: list[str] = []
        assert proc.stdout is not None

        for raw_line in proc.stdout:
            line = raw_line.strip()
            if not line:
                continue
            try:
                event = json.loads(line)
            except json.JSONDecodeError:
                errors.append(line)
                continue

            event_type = event.get("type")
            if event_type == "thread.started":
                thread_id = event.get("thread_id")
                if isinstance(thread_id, str) and thread_id:
                    active_session_id = thread_id
                    if on_session_started is not None:
                        on_session_started(thread_id)
            elif event_type in ("item.started", "item.completed"):
                item = event.get("item")
                if not isinstance(item, dict):
                    continue
                item_type = item.get("type")
                if event_type == "item.completed" and item_type == "agent_message":
                    text = item.get("text")
                    if isinstance(text, str) and text.strip():
                        result_text = text
                        self.log(f"[runner] {_clip(text.strip(), 500)}")
                elif event_type == "item.started" and item_type == "command_execution":
                    command = item.get("command", "?")
                    self.log(f"[runner] command: {_clip(str(command), 300)}")
                elif event_type == "item.started" and item_type:
                    self.log(f"[runner] item: {item_type}")
            elif event_type == "turn.completed":
                usage = event.get("usage")
                if isinstance(usage, dict):
                    total = usage.get("output_tokens")
                    self.log(f"[runner] turn completed (output_tokens={total})")
                break
            elif event_type in ("turn.failed", "error"):
                detail = event.get("error") or event.get("message") or event
                if isinstance(detail, str):
                    errors.append(detail)
                else:
                    errors.append(json.dumps(detail, ensure_ascii=False))

        return result_text, active_session_id, "\n".join(errors)

    @staticmethod
    def _wait_for_exit(proc: subprocess.Popen, timeout: float = 10.0) -> None:
        try:
            proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
